[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "connect"
authors = [{name = "Matthew Sherwood", email = "matt.sherwood@wright.edu"}]
dynamic = ["version", "description"]
